### ISSUE TITLE
Correct color channels/pixelformat for inference withexported model from custom vision

### ISSUE THREAD

**Issue by dozip** [Azure-Samples/customvision-export-samples#3]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### OS and Version?
> Windows10

Hi everyone,

my question/remark is two-folded and concerns the provided predict.py functions for different model types, tasks and domains for python(find here: https://github.com/Azure-Samples/customvision-export-samples/tree/main/samples/python):

1) Which is the correct color space of images used for inference with exported models from custom vision?

When i download models, the metadata_properties.json always says that the pixelformat is RGB8. The predict functions on the other hand (almost - see 2nd point) all contain a convertion to BGR like: input_array = input_array[:, :, :, (2, 1, 0)]  # => BGR.
Why is that and which color space/pixelformat is used for training?

2) The mentiond color space conversion is not part of the predict function for the following combination: model type ->tensorflow, task->classification, domain -> General compact [S1] (find here: https://github.com/Azure-Samples/customvision-export-samples/blob/main/samples/python/tensorflow/classification_s1/predict.py).
Why is that? Or is it just missing?

Thanks alot in advance

**Comment by shonohs** [comment]
Thanks for the questions.

1. It might be a bug in metadata_properties. Most of non-S1 models actually require BGR[0-255] inputs. Let us investigate the issue. I will keep you posted.
2. This is by design. S1 models expect RGB input.

**Comment by dozip** [comment]
Thanks for the fast response.

Concerning the 2) question:
Does this only apply for the S1 domain for classification? Because it seems that the predict.py functions for object_detection_s1 also convert to BGR.

**Comment by shonohs** [comment]
Well spotted! Thanks! It looks like our sample scripts for tensorflow has the bug.

**Comment by shonohs** [comment]
It turned out that metadata.json is for an internal training pipeline, not for an exported onnx/tensorflow/coreml model. We will update the README file to make it clear.
