### ISSUE TITLE
Examples of Classification (C#) are no longer available

### ISSUE THREAD

**Issue by jiachengng** [Azure-Samples/customvision-export-samples#5]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Examples of Classification (C#) is no longer available

### Any log messages given by the failure
> Github error 404 not found

### Expected/desired behavior
> Code for Classification (C#)

### Mention any other details that might be useful
It seems that the code has been removed or unavailable
> ---------------------------------------------------------------

**Comment by jiachengng** [comment]
May I know if there is any support or enhancement for this repository?

**Comment by shonohs** [comment]
Sorry for late response. We've added the example by #6
