### ISSUE TITLE
Example for android application

### ISSUE THREAD

**Issue by mapo80** [Azure-Samples/customvision-export-samples#7]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

Do you have any example for Android and custom S1 model TFLite?

**Comment by shonohs** [comment]
Hello,

Thanks for the feedback. But I'm afraid that we don't have a plan to implement Android + S1 model example. 

TensorFlow Lite has a good documentation and samples for image classification and object detection models. I think we just need a minor input/output change to make them work with a S1 model. https://www.tensorflow.org/lite/android

**Comment by mapo80** [comment]
Hi @shonohs,

thanks for your answer. I've implemented an android application for compact S1 downloaded from Custom Vision:
https://github.com/mapo80/CustomVisionGeneralCompactS1Android

Thanks for your help!

**Comment by shonohs** [comment]
Thanks for sharing!
